### ISSUE TITLE
Need a logo for the library.

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/resize-observer-hook#11]
We need some sort of logo for the library. So, if you are a Graphic designer and wanted to contribute to the open source community then here's your good chance.

**Comment by Gautam-Arora24** [comment]
Thank you so much @mehanalavimajd 🙂

I have used `Canva` before and I found it very useful for design purposes. Also, the logo for panix.js looks awesome and well animated. Currently, I am a bit occupied with some other stuff so do you mind picking up this issue?

**Comment by mehanalavimajd** [comment]
OK .

**Comment by Gautam-Arora24** [comment]
Thanks! I am assigning the issue to you :)

**Comment by mehanalavimajd** [comment]
![Resize Observer Hook](https://user-images.githubusercontent.com/74927578/132009429-cc1cb84a-27f5-4ad0-9e49-ec029d426597.png)
This is the logo that I want to use it , and I think it's better to add resize observer hook" name in the rectangle .
Do you like it?

**Comment by Gautam-Arora24** [comment]
Can we try making this a bit more colorful? Right now, the logo looks very simple.

**Comment by mehanalavimajd** [comment]
which color do you prefer?

**Comment by Gautam-Arora24** [comment]
@mehanalavimajd Not any specific color. You can choose any color that is vibrant and eye-catching 🙂

**Comment by mehanalavimajd** [comment]
![Resize Observer Hook (1)](https://user-images.githubusercontent.com/74927578/132021480-4e6c8924-8f8f-4ed0-8941-33671d0741eb.png)
what about this ? 
I used yellow and it's complement , purple . I also changed the rectangle/

**Comment by Gautam-Arora24** [comment]
Thanks! This looks completely awesome. Just few things to note.
- Just add hyphens between the initials.
- A little animation will help a lot.

After this you can create a PR.

**Comment by mehanalavimajd** [comment]
Do you want gif or mp4?

**Comment by Gautam-Arora24** [comment]
GIF will serve the purpose.
