### ISSUE TITLE
Add a CONTRIBUTION.md file.

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/resize-observer-hook#12]
Currently, we lack on documentation on how the beginners should start contributing to the library. We should add a `CONTRIBUTION.md` file that will contain all the information required by the beginners to start contributing.

The key points on the documentation/file will include - 

- Development environment required before contributing.
- Git principles that should be followed while contributing to the library. 
- The code style.
- How to claim an issue?
- How to make a successful Pull Request?

**Comment by daniellekush** [comment]
Hey, I'm a beginner though I'd love to help you out with this!

**Comment by Gautam-Arora24** [comment]
Thank you so much @daniellekush for your interest 🙂  I am assigning this issue to you. 
Once a PR is ready we can discuss on what can be added more or removed.

**Comment by Gautam-Arora24** [comment]
@daniellekush Are you working on this issue?

**Comment by Gautam-Arora24** [comment]
Closing this issue and creating a new one to attract contributors.
