### ISSUE TITLE
Features support that can be added.

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/resize-observer-hook#19]
### Discussed in https://github.com/Gautam-Arora24/resize-observer-hook/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **Gautam-Arora24** September 25, 2021</sup>
I just wanna know from the community members that what new features can be added to the library's scope?

</div>

**Comment by nikhilmaske-2001** [comment]
I don't know if this features can be added in this same repo, but let me share the ideas:
1. Get background color on a click
2. Get text size, color, tag (like h3, h1 etc)

**Comment by Gautam-Arora24** [comment]
Kindly refer [discussions](https://github.com/Gautam-Arora24/resize-observer-hook/discussions/17).
