### ISSUE TITLE
Remove the `--save` configuration from the npm install command in README.md

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/resize-observer-hook#26]
As of npm 5.0.0, installed modules are added as a dependency by default, so the --save option is no longer needed. We can safely remove the `--save` configuration from the command written in the README.md file.

New command ->
`` npm install resize-observer-hook``

**Comment by sarthakvaishnav09** [comment]
I would like to work on this

**Comment by Gautam-Arora24** [comment]
@sarthakvaishnav09 Go ahead :)
