### ISSUE TITLE
Add a CONTRIBUTING.md file.

### ISSUE THREAD

**Issue by Gautam-Arora24** [Gautam-Arora24/resize-observer-hook#29]
Currently, we lack documentation on how beginners should start contributing to the library. We should add a `CONTRIBUTING.md` file that will contain all the information required by the beginners to start contributing.

The key points on the documentation/file will include -

- Development environment required before contributing.
- Git principles that should be followed while contributing to the library.
- The code style.
- How to claim an issue?
- How to make a successful Pull Request?

**Comment by keshavgbpecdelhi** [comment]
I m working on it, if it needed to be assign then assigne me.

**Comment by Gautam-Arora24** [comment]
Thanks, @keshavgbpecdelhi for showing interest in this issue. Go ahead :)
